site_name: RingCentral SDK for C Sharp Simple
site_url: https://github.com/grokify/ringcentral-sdk-csharp-simple
repo_url: https://github.com/grokify/ringcentral-sdk-csharp-simple.git
docs_dir: docs
theme: readthedocs
pages:
# Introduction:
- ['index.md', 'About', 'RingCentral SDK Simple']

## Installation:
- ['installation/Visual-Studio-2015.md', 'Installation', 'Visual Studio 2015']
- ['installation/Xamarin-Android.md', 'Installation', 'Xamarin Android (Mac)']
- ['installation/Xamarin-iOS.md', 'Installation', 'Xamarin iOS (Mac)']
- ['installation/Xamarin-NET.md', 'Installation', 'Xamarin .NET (Mac)']